# image will be published to ghcr.io/<user>/<name>
name: hyprite
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite
image-version: stable # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copies config/files/usr into your image's /usr.
                  # put configuration files you want in /etc/ on a booted system 
                  # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%OS_VERSION%/solopasha-hyprland-fedora-%OS_VERSION%.repo
    install:
      # hyprland
      - hyprland
      - hyprpaper # wallpaper util      
      - hyprpicker # color    
      - hyprshot # screenshot util
      - xdg-desktop-portal-hyprland # desktop portal
      - hypridle
      - eww-wayland
      - rofi-wayland

      # audio
      - pavucontrol
      - pipewire
      - playerctl
      - wireplumber

      # bluetooth
      - blueman

      # terminal
      - starship # prompt
      - fish # shell
      
      # modern cli tools https://github.com/ibraheemdev/modern-unix
      - duf
      - eza
      - fd-find
      - httpie
      - procs
      - tldr

      # network
      - network-manager-applet
      - NetworkManager-l2tp-gnome
      - NetworkManager-libreswan-gnome
      - NetworkManager-openconnect-gnome      
      - NetworkManager-openvpn-gnome
      - NetworkManager-pptp-gnome
      - NetworkManager-sstp-gnome
      - NetworkManager-vpnc-gnome

      # qt
      - qt5-qtwayland
      - qt6-qtwayland

      # other
      - bolt
      - brightnessctl
      - dunst # notification daemon
      - fprintd-pam
      - gnome-keyring-pam
      - lxqt-policykit
      - nautilus
      - pinentry-gnome3
      - plymouth-system-theme
      - rofi-wayland
      - system-config-printer
      - waybar
      - wl-clipboard

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
